### ISSUE TITLE
Importing as ES6 module in an ember-cli project

### ISSUE THREAD

**Issue by gnapse** [kurko/ember-indexeddb-adapter#24]
Hi,

I'm trying to use this adapter in a project I just created with ember-cli v0.1.6.

I was able to successfully load it as a bower dependency with the following command:

    $ bower install git://github.com/kurko/ember-indexeddb-adapter.git --save

My app is built and loads fine in the browser, but when I try to configure the App object to use this adapter, I need to import the module. Here's the code I've got in my `app.js` file:

```javascript
import Ember from 'ember';
import DS from 'ember-data';
import Resolver from 'ember/resolver';
import loadInitializers from 'ember/load-initializers';
import config from './config/environment';
import IndexedDBAdapter from 'ember-indexeddb-adapter';

Ember.MODEL_FACTORY_INJECTIONS = true;

var App = Ember.Application.extend({
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix,
  Resolver: Resolver,

  ApplicationStore: DS.Store.extend({
    adapter: IndexedDBAdapter.extend({
      databaseName: 'tecnet-webmovil',
      version: 1,
      migrations: function() {
        @addModel('notification');
      },
  }),
});

loadInitializers(App, config.modulePrefix);

export default App;
```

However, the import that comes last, which is supposed to load this adapter library, makes the loader output this error in the console:

    Could not find module ember-indexeddb-adapter

If I drop this line, then I get the following error:

    Uncaught ReferenceError: IndexedDBAdapter is not defined

Any hints on how to solve this?

**Comment by mattmarcum** [comment]
You will need to do an `App.import(...bower_directory+indexeddb...)` in your Brocfile...

...one caveat - this adapter does not work with the latest ember-data beta - I think it stopped working around beta8 or so...

**Comment by kurko** [comment]
:scream: I am not using it right now, so I haven't tested it otherwise I'd make sure it's up to date. Anyone using this would like to send a PR updating it?

**Comment by gnapse** [comment]
@mattmarcum's solution above worked fine. Also it's worth mentioning that I'm currently using this adapter in the aforementioned project, alongside ember-data 1.0.0-beta.14.1. No problems so far.

**Comment by kurko** [comment]
Would you send a PR to update README about beta14.1 support? That'd be so
kind :D

**Comment by gnapse** [comment]
Well, I'm ok with doing it, but I cannot reliably put in the README "fully tested", as it says now about beta 7. All can say is that I have an app with a single model (no associations so far), and the usual CRUD operations work fine.

**Comment by kurko** [comment]
Gotcha. Thanks.

**Comment by mattmarcum** [comment]
The problems this adapter has are specifically with relations wrt ember
data b8+

**Comment by gnapse** [comment]
Thanks @mattmarcum, good to know. I'll be adding an association soon, so I'll update this thread with me results.
